import type { Patient } from "./types"

export const patients: Patient[] = [
  {
    id: "1",
    name: "Jane Smith",
    age: 62,
    diagnosis: "Breast Cancer Stage II",
    riskLevel: "Medium",
    status: "Stable",
    lastUpdate: "2 days ago",
    avatar: "/contemplative-artist.png",
  },
  {
    id: "2",
    name: "Robert Johnson",
    age: 71,
    diagnosis: "Lung Cancer Stage III",
    riskLevel: "High",
    status: "High-Risk",
    lastUpdate: "Today",
    avatar: "/contemplative-elder.png",
  },
  {
    id: "3",
    name: "Maria Garcia",
    age: 54,
    diagnosis: "Colorectal Cancer Stage I",
    riskLevel: "Low",
    status: "Stable",
    lastUpdate: "1 week ago",
    avatar: "/contemplative-artist.png",
  },
  {
    id: "4",
    name: "David Lee",
    age: 67,
    diagnosis: "Prostate Cancer",
    riskLevel: "Medium",
    status: "Awaiting Upload",
    lastUpdate: "3 days ago",
    avatar: "/thoughtful-urbanite.png",
  },
  {
    id: "5",
    name: "Sarah Williams",
    age: 45,
    diagnosis: "Thyroid Cancer",
    riskLevel: "Low",
    status: "Stable",
    lastUpdate: "5 days ago",
    avatar: "/placeholder.svg?height=40&width=40&query=young woman",
  },
  {
    id: "6",
    name: "Michael Brown",
    age: 59,
    diagnosis: "Melanoma Stage II",
    riskLevel: "Medium",
    status: "New Patient",
    lastUpdate: "Just now",
    avatar: "/placeholder.svg?height=40&width=40&query=middle aged man",
  },
]
